name: iOS CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: macos-13    # 改用 macOS 13

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.2.app
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Show available destinations
      run: xcodebuild -project CustomPopWindow.xcodeproj -scheme CustomPopWindow -showdestinations
      
    - name: Build and Test
      run: |
        xcodebuild clean test -project CustomPopWindow.xcodeproj -scheme CustomPopWindow -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2' -enableCodeCoverage YES | xcpretty && exit ${PIPESTATUS[0]}
    
    # 可选：使用 SwiftLint 进行代码规范检查
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging
      
    # 可选：上传测试覆盖率报告
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
