name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    env:
      PROJECT_NAME: CustomPopWindow
      TEST_SCHEME: CustomPopWindowTests  # 明确指定测试Scheme

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 选择Xcode版本（必须步骤）
      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app

      # 3. 构建项目
      - name: Build Project
        run: |
          xcodebuild build \
          -project "$PROJECT_NAME.xcodeproj" \
          -scheme "$PROJECT_NAME" \
          -destination "platform=iOS Simulator,name=iPhone 16 Pro Max"

      # 4. 运行单元测试（关键修复）
      - name: Run Unit Tests
        run: |
          xcodebuild test \
          -project "$PROJECT_NAME.xcodeproj" \
          -scheme "$TEST_SCHEME" \
          -destination "platform=iOS Simulator,name=iPhone 16 Pro Max"
