name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    env:
      PROJECT_NAME: CustomPopWindow

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 选择Xcode版本
      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app

      # 3. 构建和测试项目
      - name: Build and Test
        run: |
          xcodebuild test \
          -project "$PROJECT_NAME.xcodeproj" \
          -scheme "$PROJECT_NAME" \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro" \
          -enableCodeCoverage YES

      # 4. 可选：输出测试结果
      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: /tmp/*.xcresult
